### ISSUE TITLE
0.7.0 update

### ISSUE THREAD

**Issue by djsutherland** [conda-forge/fs.sshfs-feedstock#1]
0.7.0 came out since you started the original recipe.

The wheel files now include `COPYING`, but not the source tarballs yet: https://github.com/althonos/fs.sshfs/issues/5.

**Comment by althonos** [comment]
I just released `v0.7.1` including your `MANIFEST` as well.

**Comment by ReimarBauer** [comment]
@dougalsutherland while 0.7.1. is now merged I recognized there is no  appveyor build done.
I had removed the selector beforehand. Why is the windows build missing?
