### ISSUE TITLE
windows version missing on conda-forge

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/fs.sshfs-feedstock#5]
In the past version I disabled windows build but the 0.7.1 is capable to build on windows, tried that on one of our machines.

@jakirkham:  What is missing to get it done on conda-forge?

**Comment by jakirkham** [comment]
Have you re-rendered the feedstock after removing the `skip`?

**Comment by ReimarBauer** [comment]
thx, done by @dougalsutherland 
I missed that completly :)
